# Generated by Django 5.0.2 on 2024-03-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=800)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=800)),
                ('last_name', models.CharField(max_length=800)),
                ('father_name', models.CharField(max_length=800)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('job_title_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.jobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOnTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('work_time', models.IntegerField(default=0)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.user')),
            ],
        ),
    ]
