# Generated by Django 5.0.2 on 2024-04-02 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=800)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=800)),
                ('daysToAccomplish', models.IntegerField(default=0)),
                ('stageAt', models.CharField(default='Nothing', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='todo',
            field=models.ManyToManyField(to='essential.task'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(default='https://www.svgrepo.com/show/192244/man-user.svg', max_length=800)),
                ('age', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=800)),
                ('last_name', models.CharField(max_length=800)),
                ('father_name', models.CharField(max_length=800)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('position', models.CharField(default='работник', max_length=800)),
                ('job_title_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.jobtitle')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(to='essential.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='essential.user'),
        ),
        migrations.CreateModel(
            name='UserWithTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=800)),
                ('work_date', models.DateField(null=True)),
                ('work_time', models.IntegerField(null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.user')),
            ],
        ),
    ]
