# Generated by Django 5.0.2 on 2024-04-23 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=800)),
                ('hoursToAccomplish', models.IntegerField(default=0)),
                ('stageAt', models.CharField(choices=[('F', 'исправлено'), ('N', 'требует исправления')], default='N', max_length=30)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.project')),
                ('workers', models.ManyToManyField(to='essential.user')),
            ],
        ),
    ]
