# Generated by Django 5.0.2 on 2024-04-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0002_issues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
