# Generated by Django 5.0.2 on 2024-04-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0003_user_tasks_userprojectsandtasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='daysToAccomplish',
            new_name='hoursToAccomplish',
        ),
        migrations.RemoveField(
            model_name='project',
            name='todo',
        ),
    ]
