# Generated by Django 5.0.2 on 2024-04-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0004_rename_daystoaccomplish_task_hourstoaccomplish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
    ]
