# Generated by Django 5.0.2 on 2024-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0004_rename_daystoaccomplish_task_hourstoaccomplish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('W', 'Работник'), ('B', 'Руководитель')], default='W', max_length=800),
        ),
        migrations.DeleteModel(
            name='UserWithTask',
        ),
    ]
