# Generated by Django 5.0.2 on 2024-04-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0005_remove_user_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
