# Generated by Django 5.0.2 on 2024-04-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0005_alter_task_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.user')),
            ],
        ),
    ]
