# Generated by Django 5.0.2 on 2024-04-30 18:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0007_user_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWIthTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('T', 'task'), ('I', 'issue')], default='task', max_length=80)),
                ('work_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.user')),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essential.task')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProjectsAndTasks',
        ),
    ]
