# Generated by Django 5.0.2 on 2024-05-01 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0008_userwithtask_delete_userprojectsandtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userwithtask',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
